### ISSUE TITLE
远程工具 类似 'RDP'的 相关使用和体验咨询

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#10]
您好, 当我希望从一台安装了Windows 操作系统的电脑, 通过类似 rdp方案, 连接到安装了anduin OS 的操作系统,并获得类似RDP的图形操作体验时, 我应当如何在anduin OS 操作系统内进行相应的配置/设置?     
通常情况下,形如VNC等方案的 用户体验,比起RDP方案的体验差距明显, 期望有近似于RDP的使用效果;  

Q2: 如何在anduinOS操作系统内,通过类似RDP的工具 ,链接到另一台windows设备,并进行基于图形界面的远程操作?

**Comment by Anduin2017** [comment]
```bash
sudo apt install remmina
```

**Comment by rdfsource** [comment]
当我早些时候按照指导进行操作时, 似乎出现了 登录成功之后,rdp退出的现象. 

参考了(csdn帖子)[https://blog.csdn.net/Pipcie/article/details/84974561]  
执行如下操作后,rdp可以连接,不过此时桌面显示有点儿诡异
```bash
sudo apt-get install xfce4
echo xfce4-session > ~/.xsession
touch .session
sudo vim /etc/xrdp/startwm.sh
在. /etc/X11/Xsession前面加
xfce4-session

然后重启 sudo service xrdp restart。
```

![诡异桌面](https://github.com/user-attachments/assets/d269eadf-6600-4bcd-87ed-653dc15bbf48)


在这之后,咨询了群友,经过建议,参考了[博客](https://shubuzuo.aiursoft.cn/post/2023/8/16/xrdp-centos)  中的相关内容,并最终通过引导页面的[集成脚本](https://www.c-nergy.be/products.html ),修复了一些信息后,rdp连接和桌面显示成功.

![桌面显示成功](https://github.com/user-attachments/assets/466fdb39-eaa1-4a1c-98f8-1437aac94549)

**Comment by Anduin2017** [comment]
恭喜。别忘了，你需要右键 Chrome 的图标，选择 “允许执行”，才可以双击运行它。
