### ISSUE TITLE
打印扫描一体机 Epson L6468 其中扫描仪 驱动安装/使用的困惑

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#11]
笔者原意咨询打印扫描一体的机驱动安装问题,在尝试过程中,已解决打印机驱动问题,现咨询 扫描仪驱动相应问题.

您好,我使用的打印机是 Epson L6468型号. 当我安装完成anduinOS, 我期望将这台设备链接上我的IP打印机/扫描仪一体机, 目前这台打印机在内网的IP是 192.168.20.99, 其它Windows设备可以正常搜索到它,并安装好打印机和扫描仪驱动. 

在anduinOS中, 我登录了爱普生官网查询该设备的信息,其中只有'国产化'操作系统提供了对应的linux驱动, 我尝试下载了
epson-inkjet-printer-escpr2_1_1_13_CLOS_amd64.deb文件,并在系统中安装成功,打印测试页成功.
[驱动地址](https://www.epson.com.cn/services/search.html?key=6468)

目前咨询:
我通过页面下载了一体机的扫描仪驱动:
epsonscan2-non-free-plugin_1_0_0_6-1_amd64.deb
epsonscan2_6_7_62_10-1_amd64.deb
在系统内安装成功, 在'所有程序'中,可以看到 Epson Scan 2 程序,但是点击之后 无反应, 期待建议的处理/尝试方案.

**Comment by Anduin2017** [comment]
看起来你已经成功安装了Epson L6468的一体机驱动，但在使用Epson Scan 2扫描软件时遇到了无响应的问题。以下是一些针对该问题的解决方案，帮助你进一步排查和解决：

1. **检查缺失的依赖项**：
   你可以通过终端运行以下命令，确保系统中所有必要的依赖项和库都已安装：
   ```bash
   sudo apt update
   sudo apt --fix-broken install
   sudo apt install lsb
   ```
   这将确保你的系统具备Epson Scan 2运行所需的所有库文件。

2. **从终端运行程序**：
   通过终端直接运行Epson Scan 2，可能会提供更多的错误信息，帮助你分析问题所在。运行以下命令：
   ```bash
   /usr/bin/epsonscan2
   ```
   如果有错误信息，请将其反馈，这样可以更好地帮助你解决问题。

3. **检查网络连接**：
   因为你的设备通过网络连接，首先确保系统能够访问到打印机/扫描仪所在的IP地址。通过以下命令进行网络连接检查：
   ```bash
   ping 192.168.20.99
   ```
   确保防火墙或其他安全设置没有阻止网络通信。

4. **检测扫描仪是否被识别**：
   你可以通过 `sane` 工具来检查系统是否识别到了扫描仪。运行以下命令：
   ```bash
   scanimage -L
   ```
   如果能够识别到扫描仪，说明驱动已经正常工作，问题可能出现在Epson Scan 2软件本身。

5. **查看系统日志**：
   使用以下命令查看系统日志，可能有助于你定位启动Epson Scan 2时出现的潜在问题：
   ```bash
   journalctl -xe
   ```

6. **尝试使用Simple Scan工具**：
   作为临时解决方案，你可以使用Ubuntu自带的`Simple Scan`工具来测试扫描功能：
   ```bash
   sudo apt install simple-scan
   simple-scan
   ```
   这可以帮助你确认扫描仪的基础功能是否正常。

如果在执行这些步骤后遇到任何错误信息或进一步的问题，请分享详细信息，我可以为你提供更具体的解决方案。
