### ISSUE TITLE
文件拷贝的'暂停'功能咨询

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#16]
在windows 操作系统使用时, 支持客户点击暂停按钮,终止一个/一批正在拷贝/处理的文件, 在Linux系统中, 是否存在/可能存在类似的概念实现?

**Comment by Anduin2017** [comment]
在运行 cp 命令的时候直接按下键盘上的 Ctrl + C 即可。

**Comment by samwhelp** [comment]
## nautilus

在「Gnome Shell」，內建的「檔案管理器」是「[nautilus](https://manpages.ubuntu.com/manpages/plucky/en/man1/nautilus.1.html)」。

以下我用複製「AnduinOS.iso (大檔案)」來測試，

在左下方，會出現如下圖的提示訊息，

![nautilus-copying-1](https://github.com/user-attachments/assets/fe58b7a1-35c1-4474-97a8-fd5376a4e863)

點選它，接著就會出現如下圖的對話框。

![nautilus-copying-2](https://github.com/user-attachments/assets/17aafd69-3da6-4a33-960a-488b4fdbf242)

可以了解到「`nautilus`」目前只有實作「`取消`」的功能。




## thunar

我們也可以安裝其他的「檔案管理器」來測試。

執行下面指令，安裝「[thunar](https://packages.ubuntu.com/plucky/thunar)」。

``` sh
sudo apt install thunar
```

一樣複製「AnduinOS.iso (大檔案)」來測試，就會出現一個對話框，類似下面的圖片

![thunar-copying](https://github.com/user-attachments/assets/c93f32e9-b934-4f79-a776-761f18c47919)

可以了解到「`thunar`」有實作「`暫停`」和「`取消`」的功能。




## pcmanfm

執行下面指令，安裝「[pcmanfm](https://packages.ubuntu.com/plucky/pcmanfm)」。

``` sh
sudo apt install pcmanfm
```

一樣複製「AnduinOS.iso (大檔案)」來測試，就會出現一個對話框，類似下面的圖片

![pcmanfm-copying](https://github.com/user-attachments/assets/1d114cde-dcbd-4445-8784-90726be5656a)

可以了解到「`pcmanfm`」也有實作「`暫停`」和「`取消`」的功能。

**Comment by Anduin2017** [comment]
从用户态的角度，实现暂停是完全可行的。毕竟拷贝就是一段一段的拷贝，暂时不要拷贝下一段就暂停了。

感谢 @samwhelp 指出了可行的应用！
