### ISSUE TITLE
'开始菜单'概念定位问题咨询

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#17]
您好, 通过您的[解答](https://github.com/Anduin2017/AnduinOS/issues/10),我已成功实现了remmina,xrdp相关的应用.

我已成功链接上了扫描仪,并扫描测试成功,  执行完[指导](https://github.com/Anduin2017/AnduinOS/issues/11) 的检查项1 后,运行2时,已成功运行,并完成了扫描测试. 非常感谢.
 
阅读'暂停'功能的相应[回复](https://github.com/Anduin2017/AnduinOS/issues/16),似乎操作本身更有趣了.感性的认知 是更灵活了

阅读'几点细节问题咨询'的[回复](https://github.com/Anduin2017/AnduinOS/issues/15), ⑴,快捷键非常好用,谢谢. ⑵,您的回复启发了我对于 闭源软件 的一些思考,非常感谢. 我会进行一些尝试. 对于僵化,过度依赖的部分应用,将尝试改善,似乎是个长期的过程.  若客户方在僵化行为模式前提下只要个结果的,可能我倾向于参考 [统信](https://github.com/zq1997/deepin-wine)相关的第三方方案,快速应对过去 . 但是您的回复,更新了我对于开源世界的一些认知,也开始反思 自己的哪些'意识' 是闭源软件开发商有意影响或'植入'的.

本帖期望咨询的一个问题:

您好,我已经将'任务栏'调整为自己习惯使用的个性化显示方案,但是在我点击类似'开始按钮'的图标时, 开始菜单依旧显示在屏幕中间, 我期望将它调整到左上角显示, 或者当任务栏处于屏幕右边时,将开始菜单显示在屏幕右上角. 请问我可以如何实现期望的这个行为?

简易截图如下:
![开始菜单定位](https://github.com/user-attachments/assets/205c8be3-41b4-44d1-9a81-12a5487f709a)

**Comment by Anduin2017** [comment]
![image](https://github.com/user-attachments/assets/9095c6ce-66cb-4cb6-923a-9343d75d80a0)

右键点击 开始按钮，选择 `ArcMenu Settings`(开始菜单设置）

选择 `menu` 菜单，选择`Menu Visual Appearance` 菜单可视化效果：

![image](https://github.com/user-attachments/assets/f37a8012-8097-4367-af8f-34762223e17b)

 把 `Override Menu Location` 覆盖菜单位置 改为 Off 即可。

**Comment by Anduin2017** [comment]
https://docs.anduinos.com/Install/Personalize-Your-Desktop.html

增加了这部分文档介绍如何个性化任务栏。

你可以参考这些命令：


# Personalize Your Desktop

You can personalize your desktop by changing the wallpaper, theme, and element locations. This guide will show you how to personalize your desktop.

## Change taskbar position

You can change the taskbar position to the top, bottom, left, or right of the screen.

### Move taskbar to the bottom, and center the start menu

```
curl -sL https://gitlab.aiursoft.cn/anduin/anduinos/-/raw/master/src/styles/bottom_center.ini | dconf load /org/gnome/
```

![bottom-center](https://docs.anduinos.com/Install/styles/1.png)

---

### Move taskbar to the bottom, and put the start menu on the left

```
curl -sL https://gitlab.aiursoft.cn/anduin/anduinos/-/raw/master/src/styles/bottom_left.ini | dconf load /org/gnome/
```

![bottom-left](https://docs.anduinos.com/Install/styles/2.png)

---

### Move taskbar to the left, and center the start menu

```
curl -sL https://gitlab.aiursoft.cn/anduin/anduinos/-/raw/master/src/styles/left_center.ini | dconf load /org/gnome/
```

![left-center](https://docs.anduinos.com/Install/styles/3.png)

---

### Move taskbar to the left, and put the start menu on the top

```
curl -sL https://gitlab.aiursoft.cn/anduin/anduinos/-/raw/master/src/styles/left_top.ini | dconf load /org/gnome/
```

![left-top](https://docs.anduinos.com/Install/styles/4.png)

---

### Move taskbar to the top, and center the start menu

```
curl -sL https://gitlab.aiursoft.cn/anduin/anduinos/-/raw/master/src/styles/top_center.ini | dconf load /org/gnome/
```

![top-center](https://docs.anduinos.com/Install/styles/5.png)

---

### Move taskbar to the top, and put the start menu on the left

```
curl -sL https://gitlab.aiursoft.cn/anduin/anduinos/-/raw/master/src/styles/top_left.ini | dconf load /org/gnome/
```

![top-left](https://docs.anduinos.com/Install/styles/6.png)

---

### Move taskbar to the right, and center the start menu

```
curl -sL https://gitlab.aiursoft.cn/anduin/anduinos/-/raw/master/src/styles/right_center.ini | dconf load /org/gnome/
```

![right-center](https://docs.anduinos.com/Install/styles/7.png)

---

### Move taskbar to the right, and put the start menu on the top

```
curl -sL https://gitlab.aiursoft.cn/anduin/anduinos/-/raw/master/src/styles/right_top.ini | dconf load /org/gnome/
```

![right-top](https://docs.anduinos.com/Install/styles/8.png)
