### ISSUE TITLE
关于字体与输入法

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#19]
您好: 
Communication:
基于某些情况,笔者需要使用到'微软雅黑''这一字体.基于部分客观授权与指导方向等原因,借由[帖子](https://cloud.tencent.com/developer/article/2404833) 已实现这一操作.

Question:
关于输入法,目前在win系统下,使用 搜狗输入法[sogou_pinyin_zhihui_83b.exe](https://pinyin.sogou.com/zhihui/),并且开启了 '搜狗卷轴'这一选项,它带给了我一些更好的体验.

![卷轴1](https://github.com/user-attachments/assets/86664410-bc63-4bcb-a4a4-75adcb2a72dd)

![卷轴2](https://github.com/user-attachments/assets/17435d8e-28ce-4cbd-b528-031f6a4d8639)

![卷轴3](https://github.com/user-attachments/assets/f49c1f28-11b9-4699-8650-388c21179d68)

正常打字时,显示5个候选选项(可自定义), 而当我开启 '搜狗卷轴'这一配置项后, 可以实现 通过方向键开启下几层的选项展示.在此界面内,可以极大提高输入选项的观测效率,咨询是否有可能在anduinOS中实现这一效果?  同时,期望咨询,是否有可能记忆常用词的词频,在输入时,逐步前置, 亦考虑 导入,导出,对应记忆的配置

**Comment by Anduin2017** [comment]
您好，非常感谢您的反馈和建议。关于您提到的“搜狗卷轴”功能以及词频记忆的需求，我要说明一下，AnduinOS当前默认安装的是ibus输入法。而这些功能更属于输入法本身的特性，因此建议您直接向ibus项目提交相关的功能请求。

ibus输入法支持各种自定义设置和插件扩展，可能已经有类似功能或可以通过配置实现。如果需要的话，您也可以在ibus的文档或社区中寻找是否有解决方案。
