### ISSUE TITLE
原子性操作求解

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#22]
您好, 目前我正在vm环境下执行系统/环境迁移的前期求解/筹备工作.当我使用vm进行单一项目的测试时, 操作执行前,可以执行'快照',当操作出现不可预计的行为,或在过程中使用到了部分超出权限的行为测试,(如root用户操作导致的一些非预期结果),或迁移过程中 兼容性/其他问题导致的结果. 基于这些非特定的结果,我期望将系统状态 '回档'到操作之前, 此时, vm中的快照,可以让我快速实现这一行为; 当我使用macOS时, time machine亦可以使我达到相同的目的. 而对于anduinOS, 我期望通过优雅的方式,实现这个效果. 

这个概念的提出,可以进一步让用户的操作,实现近似'原子性'的追求,目标用户可能处于非虚拟化的环境, 无法通过上层设施,实现快照,或者类似的概念. 在macOS的系统中,这一需求借由时间胶囊,在系统层面,提供了优雅的可选支持,操作人员的试错,可以借由timemachine中复多种杂机制 实现近似'回档'的效果. 期望可以在anduinOS中,体验到类似的效果.  

这一事项的实现, 在理论上,可以降低系统使用的'难度'. 他不代表着客观层面上,学习成本的降低, 而是对普通用户而言,可以降低自己操作本身的'风险性'. 上文中提到的root用户非常规情况,也不是推荐行为, 仅用于指代,在达到安装程序,或者 调试以实现某功能,或驱动 硬件 软件 时,可能造成的风险性操作.  笔者参考一些不成文/非常规的例子, 会有部分用户,在完全不了解行文本身将带来的后果时, 执行了一连串操作,当他们提问时,可能已经将一个简单的问题,扩大成了巨大的问题; 而受到提问的人,都不知道对方在提问前,到底干了多少事情......有多少系统本身的文件被影响/改变了  如果有个,回档的机制,让他们在行为前, 先做个'记录点', 对于后续问题的处理,将会非常有益. 

当然,本文仅做概念性的咨询,这一需求的实现,甚至GUI.  在未来是否会进一步发展为基础设施,亦仅供参考.

**Comment by Anduin2017** [comment]
AnduinOS完全支持使用ZFS（Zettabyte File System）或Btrfs（B-Tree File System）来实现快照功能。

ZFS和Btrfs是现代的文件系统，它们支持快照功能，可以在文件系统层面创建系统状态的快照。通过创建快照，您可以记录系统在某个时间点的完整状态，包括文件、目录、权限等。当出现意外情况或需要回滚到之前的状态时，您可以轻松地恢复到快照所记录的状态，而不会丢失任何数据。

使用ZFS或Btrfs的快照功能，您可以在进行操作之前创建一个快照，然后在操作过程中进行任何需要的更改。如果操作出现问题或结果不符合预期，您可以轻松地将系统状态回滚到快照所记录的状态，从而实现类似于回滚的效果。

在AnduinOS中，您可以使用命令行工具来创建和管理快照。例如，在使用ZFS时，您可以使用`zfs snapshot`命令创建快照，使用`zfs rollback`命令回滚到快照所记录的状态。如果您使用Btrfs，可以使用`btrfs subvolume snapshot`和`btrfs subvolume delete`命令来创建和删除快照。

通过使用ZFS或Btrfs的快照功能，您可以更好地管理系统状态，降低操作的风险，并在需要时轻松回滚到之前的状态。这对于系统迁移、测试和调试等场景都非常有用。

有关更多操作技巧，请参考：https://edgeneko.aiursoft.cn/2024/08/18/BtrfsWithUbuntuServer/

**Comment by rdfsource** [comment]
这似乎意味着,我需要具有一定的Linux与Btrfs相关的基础知识.  以及对于一个已经完成了常规情况下,通过默认安装方式安装和自定义完成的anduinos,是否需要从头,重新执行格式化磁盘与进行系统安装这一过程.  另外,在操作过程中,似乎感到,Linux方案下,让用户通过GUI实现需求,几乎在功能性实现的优先级上,不是前置的序列, 类似的快照方案, 操作macOS的用户,无需了解其原理.仅通过GUI方案可以快速达成需求. 当然,在了解部分Linux命令的功能性后,干到那个达成,似乎更片面一些, 但是对于非专业的选手,似乎更友好一些.这是否将其理解为,操作系统本身面向用户的类型,有所差异?

**Comment by rdfsource** [comment]
![btrfs](https://github.com/user-attachments/assets/e9a4154e-3aaa-470e-9470-bcb77a092daa)

您好: 当我尝试将系统安装为btrfs时,在安装阶段,最简/最佳分区设置是什么样的? (单盘) 我是否设置了多余的分区?

**Comment by Anduin2017** [comment]
@hv0905
