### ISSUE TITLE
登录桌面背景调整咨询

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#23]
您好: 经过一些不知名的调整后, 我的登录桌面背景变成了个黑色/灰色, 我可以通过什么操作,来恢复默认情况下的那个,带有彩色图片的登录背景?
![登录桌面的背景](https://github.com/user-attachments/assets/c6f3e341-68bd-4ccf-8b4e-2693ffdd6a22)

**Comment by Anduin2017** [comment]
登录一次就行了。
