### ISSUE TITLE
(UX) Password when opening the settings

### ISSUE THREAD

**Issue by MrOzwaldMan** [Anduin2017/AnduinOS#25]
While I understand why it's there, but people don't want to type a password every time they enter their settings. It gets annoying pretty quickly if the password has to be typed repeatedly.
![image](https://github.com/user-attachments/assets/49c65de1-66d8-4547-aa03-b3fe594fde6a)

**Comment by Anduin2017** [comment]
Hi, thanks for the feedback!!

AFAIK, setting date and time is only allowed if the user is root.

If you prefer to access root settings without typing password, please reference doc here:

https://docs.anduinos.com/Install/Allow-Sudo-Without-Password.html

And use the following command to open settings:

```bash
sudo gnome-control-center
```

No more password required.

**Comment by MrOzwaldMan** [comment]
I understand, but why isn't it **No Password** by default as standard in every other OS.

**Comment by Anduin2017** [comment]
Oh.. No password by default is a bad practice for security. Imagine every app on your computer can change your date and time is a huge vulnerbility.

**Comment by MrOzwaldMan** [comment]
Interesting, I haven't thought of that. But I prefer No Password, so I'll do the commands you mentioned above. Thanks for the OS.
