### ISSUE TITLE
(UX) Double-clicking the top bar doesn't always make the application go full screen.

### ISSUE THREAD

**Issue by MrOzwaldMan** [Anduin2017/AnduinOS#26]
This issue stems up with browser applications, or non-libadwaita apps, as I tried to double-click the top bar to full-screen **Firefox**, and **Brave**. Does it go full screen? Yes. Does it do it all the time? No. I think that's something you ought to investigate further.

**Comment by Anduin2017** [comment]
Hi! Thanks for the feedback!!

I have tried a lot of apps on my box..

![image](https://github.com/user-attachments/assets/03ec9fcb-deae-455d-9563-6ac4c60acb3f)

I found all apps can toggle fullscreen successfully.

Could you please share about how to trigger this issue?

Thanks!!

**Comment by MrOzwaldMan** [comment]
I tried **Brave**, and **Firefox** both didn't go Fullscreen successfully the first time, but after a few attempts then it went full screen.

**Comment by MrOzwaldMan** [comment]
Really, is it my machine specifically? Here are the system specifications: 
![image](https://github.com/user-attachments/assets/fe3b86e8-1f6b-4b1c-8eda-9e536dd02b81)

**Comment by Anduin2017** [comment]
https://github.com/user-attachments/assets/535fb59f-255e-467c-9777-fa1572289ea6

**Comment by MrOzwaldMan** [comment]
Understood, so this is my issue. I will try to fix this myself.
