### ISSUE TITLE
Gnome 42?

### ISSUE THREAD

**Issue by markox92** [Anduin2017/AnduinOS#3]
Is this customized Gnome 42 or am I wrong? And what's the point of trying to clone Windows 11?

**Comment by Anduin2017** [comment]
>Is this customized Gnome 42 or am I wrong?

It's gnome 42.9.

>And what's the point of trying to clone Windows 11?

I've thought carefully about this case, which is an ideal interface element layout. Firstly, I need to be able to click blindly on the top right corner to close the window and click blindly on the top center to drag the window. This is a very efficient operation habit. However, I quickly realized the problem: the taskbar must be at the bottom to free up space at the top. If the taskbar is placed on the left or right side, an additional space is always needed to display status information. When I placed the taskbar at the bottom, the next issue was how to display the application list. If it’s shown in the bottom left corner (similar to Windows 10), it becomes asymmetrical on large screens. I also want a sense of symmetry, so I had to center the applications. After making this change, I found the operation to be very efficient, but interestingly, it closely resembled Windows 11. So I thought, why not stick with it, and it can also cater to Windows 11 users' habits.

However, to my knowledge, there are many Linux distributions, such as Wubuntu, that are truly professional in this aspect. Not only do they have a UI that is very similar, but even the icons are similar, and they have created an entire set of system applications to mimic Windows 11. I think this goes too far. After all, Linux is Linux, and there’s no need to be overly obsessed with disguising itself as Windows. Therefore, operating systems like Manjaro and Deepin, as well as AnduinOS, emulate the essence of Windows 11’s interface layout and have proven that this is indeed an excellent design. However, for applications, icons, power buttons, details, settings, etc., they retain the original Linux experience.
