### ISSUE TITLE
questions about dd

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#30]
Dear Sirs:

How to using dd to achieve some goals?

⒈我想将,Windows下的VMware中已经安装完成并且使用正常的Ubuntu虚拟机,完整迁移到anduinos中, 我应当如何操作实现?

⒉ 我想将物理设备中安装的 Windows 10,变成 anduinos中的一个Windows虚拟机,我应当如何操作实现?

Ths~
Source

**Comment by Anduin2017** [comment]
1. DD the Ubuntu's system disk to a file, then create a new VM in AnduinOS, dd the file back to the VM.
2. Create a new Windows VM, dd the physical disk to the VM.

Please reference doc here to create new Windows VMs in AnduinOS.

https://docs.anduinos.com/Virtualization/Windows.html
