### ISSUE TITLE
how to change 鼠标指针大小

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#31]
Dear Sirs:
i wanna change 鼠标指针大小, and i found nothing about this at doc. After searching from CSDN, I Found a way to achieve this:
```bash
sudo apt install dconf-editor
dconf-editor
导航到  `/org/gnome/desktop/interface/cursor-size`
在右侧面板中，你可以看到 “cursor-size” 的设置。点击它，然后在 “Custom value” 字段中输入你想要的鼠标大小。点击 “Apply” 按钮应用更改。
```

这是我在期望调整鼠标指针大小时的最佳实践么?
![image](https://github.com/user-attachments/assets/b820d18c-3bf3-4b17-8adb-dd5abdbdc2b3)

**Comment by Anduin2017** [comment]
直接跑

```bash
dconf write  /org/gnome/desktop/interface/cursor-size 25
```

不就行了
