### ISSUE TITLE
ISO语言包变更方法咨询

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#32]
Dear Sirs:
执行完成./build.sh后产生AnduinOS-1.0.5-en_US-2412131859.iso文件；

期望重新编译出一个 zh_CN的ISO；

调整了args.sh文件：
export LANG_MODE="zh_CN"
export LANG_PACK_CODE="zh"

重新执行./build.sh时 ，插件商店下插件卡住
![image](https://github.com/user-attachments/assets/1f318216-7476-4f81-828b-df950d9b2faa)

我是否能换个思路，直接对已经编译完成的AnduinOS-1.0.5-en_US.iso文件 进行调整并产生一个  -zh_CN.iso 文件， 我应当如何编写 ‘changeLanguage.sh’ 以实现这个想法？

**Comment by Anduin2017** [comment]
下插件时卡住去找 gnome extensions store 问。

如果你要换个思路，例如把语言A的iso改成语言B的，你需要回滚所有面向语言A的过程，重演面向语言B的即可。

**Comment by Anduin2017** [comment]
这个问题不是一个issue。请下次去discussion。
