### ISSUE TITLE
how do you move the icons on the taskbar?

### ISSUE THREAD

**Issue by DOOMMARINE117** [Anduin2017/AnduinOS#8]
how do you move them? i just install t little bit ago.

great job. i installed this on lenovo legion go

looks like all the apps shown except for  a more updated version of dhwem3

can you add software updater?

for winetricks Your version of wine 6.0.3 is no longer supported upstream. You should upgrade to 8.x

note: command wine64 C:windowssystem32 egsvr32exe qasf.dll returned status 5. Aborting.

**Comment by DOOMMARINE117** [comment]
> how do you move them? i just install t little bit ago.
> 
> great job. i installed this on lenovo legion go

can you also add a software updater?

**Comment by DOOMMARINE117** [comment]
i figured it out how to move them

**Comment by Anduin2017** [comment]
>how do you move them? i just install t little bit ago.

Simply drag it.

>great job. i installed this on lenovo legion go

Thank you!!

>looks like all the apps shown except for a more updated version of dhwem3

Sorry but.. What is `dhwem3`?

```bash
anduin@anduin-work:~$ sudo apt show dhwem3
N: Unable to locate package dhwem3
N: Unable to locate package dhwem3
E: No packages found
```

>can you add software updater?

The problem is if I bring this to AnduinOS, it will also bring in `Ubuntu-Pro`. And I don't prefer adding it.

```bash
anduin@anduin-work:~$ sudo apt install update-notifier
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  gir1.2-goa-1.0 gir1.2-snapd-1 python3-dateutil python3-distupgrade python3-update-manager software-properties-gtk ubuntu-advantage-desktop-daemon ubuntu-advantage-tools ubuntu-pro-client ubuntu-pro-client-l10n ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk
  update-manager update-manager-core update-notifier-common
The following NEW packages will be installed:
  gir1.2-goa-1.0 gir1.2-snapd-1 python3-dateutil python3-distupgrade python3-update-manager software-properties-gtk ubuntu-advantage-desktop-daemon ubuntu-advantage-tools ubuntu-pro-client ubuntu-pro-client-l10n ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk
  update-manager update-manager-core update-notifier update-notifier-common
0 upgraded, 16 newly installed, 0 to remove and 16 not upgraded.
Need to get 1,448 kB of archives.
After this operation, 7,121 kB of additional disk space will be used.
```

>for winetricks Your version of wine 6.0.3 is no longer supported upstream. You should upgrade to 8.x

Good advice! I will try to update the document.

note: command wine64 C:windowssystem32 egsvr32exe qasf.dll returned status 5. Aborting.

**Comment by DOOMMARINE117** [comment]
> > how do you move them? i just install t little bit ago.
> 
> Simply drag it.
> 
> > great job. i installed this on lenovo legion go
> 
> Thank you!!
> 
> > looks like all the apps shown except for a more updated version of dhwem3
> 
> Sorry but.. What is `dhwem3`?
> 
> ```shell
> anduin@anduin-work:~$ sudo apt show dhwem3
> N: Unable to locate package dhwem3
> N: Unable to locate package dhwem3
> E: No packages found
> ```
> 
> > can you add software updater?
> 
> The problem is if I bring this to AnduinOS, it will also bring in `Ubuntu-Pro`. And I don't prefer adding it.
> 
> ```shell
> anduin@anduin-work:~$ sudo apt install update-notifier
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following additional packages will be installed:
>   gir1.2-goa-1.0 gir1.2-snapd-1 python3-dateutil python3-distupgrade python3-update-manager software-properties-gtk ubuntu-advantage-desktop-daemon ubuntu-advantage-tools ubuntu-pro-client ubuntu-pro-client-l10n ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk
>   update-manager update-manager-core update-notifier-common
> The following NEW packages will be installed:
>   gir1.2-goa-1.0 gir1.2-snapd-1 python3-dateutil python3-distupgrade python3-update-manager software-properties-gtk ubuntu-advantage-desktop-daemon ubuntu-advantage-tools ubuntu-pro-client ubuntu-pro-client-l10n ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk
>   update-manager update-manager-core update-notifier update-notifier-common
> 0 upgraded, 16 newly installed, 0 to remove and 16 not upgraded.
> Need to get 1,448 kB of archives.
> After this operation, 7,121 kB of additional disk space will be used.
> ```
> 
> Anyway, you can install it on your own. Simpy run the command I shared. You may also want to install `gnome-software`
> 
> > for winetricks Your version of wine 6.0.3 is no longer supported upstream. You should upgrade to 8.x
> 
> Good advice! I will try to update the document.
> 
> note: command wine64 C:windowssystem32 egsvr32exe qasf.dll returned status 5. Aborting.

awesome. so far its been smoothed. not many issues, just need to solve my issues with wine prefix.

great  job

**Comment by DOOMMARINE117** [comment]
no worries on the updater. i get it. its alot worked.

**Comment by DOOMMARINE117** [comment]
> > how do you move them? i just install t little bit ago.
> 
> Simply drag it.
> 
> > great job. i installed this on lenovo legion go
> 
> Thank you!!
> 
> > looks like all the apps shown except for a more updated version of dhwem3
> 
> Sorry but.. What is `dhwem3`?
> 
> ```shell
> anduin@anduin-work:~$ sudo apt show dhwem3
> N: Unable to locate package dhwem3
> N: Unable to locate package dhwem3
> E: No packages found
> ```
> 
> > can you add software updater?
> 
> The problem is if I bring this to AnduinOS, it will also bring in `Ubuntu-Pro`. And I don't prefer adding it.
> 
> ```shell
> anduin@anduin-work:~$ sudo apt install update-notifier
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following additional packages will be installed:
>   gir1.2-goa-1.0 gir1.2-snapd-1 python3-dateutil python3-distupgrade python3-update-manager software-properties-gtk ubuntu-advantage-desktop-daemon ubuntu-advantage-tools ubuntu-pro-client ubuntu-pro-client-l10n ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk
>   update-manager update-manager-core update-notifier-common
> The following NEW packages will be installed:
>   gir1.2-goa-1.0 gir1.2-snapd-1 python3-dateutil python3-distupgrade python3-update-manager software-properties-gtk ubuntu-advantage-desktop-daemon ubuntu-advantage-tools ubuntu-pro-client ubuntu-pro-client-l10n ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk
>   update-manager update-manager-core update-notifier update-notifier-common
> 0 upgraded, 16 newly installed, 0 to remove and 16 not upgraded.
> Need to get 1,448 kB of archives.
> After this operation, 7,121 kB of additional disk space will be used.
> ```
> 
> Anyway, you can install it on your own. Simpy run the command I shared. You may also want to install `gnome-software`
> 
> > for winetricks Your version of wine 6.0.3 is no longer supported upstream. You should upgrade to 8.x
> 
> Good advice! I will try to update the document.
> 
> note: command wine64 C:windowssystem32 egsvr32exe qasf.dll returned status 5. Aborting.

for dhwem3 is a source port for doom 3. but, im guessing every distro is different

**Comment by Anduin2017** [comment]
It's hard to upgrade the wine becaue AnduinOS simply uses Ubuntu's software repository. While the `wine64` in Ubuntu repository is `6.0.3`. You may need to manually install it.

**Comment by DOOMMARINE117** [comment]
how do you install gamescope?

**Comment by DOOMMARINE117** [comment]
i installed nightdive doom. awesome job. gaming will be smoothed compared to other distros.

**Comment by DOOMMARINE117** [comment]
python3 for lutris is 3.11. how do i update to he latest one?

**Comment by Anduin2017** [comment]
Install Python 3.12 from PPA
For Ubuntu 22.04, Ubuntu 20.04, and their derivatives such as Linux Mint 21, the [Deadsnakes PPA](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa/) has made the packages for all supported CPU architecture types: amd64, arm64/armhf, ppc64el, and s390x.

1. First, press Ctrl+Alt+T on keyboard to open terminal. Then paste the command below and hit run to add PPA:

sudo add-apt-repository ppa:deadsnakes/ppa
Type user password (no asterisk feedback) when it asks and hit Enter to continue.



2. Ubuntu 20.04+ automatically refresh package cache while adding PPA. However, Linux Mint user may need to do this job manually by running command:

sudo apt update
3. Finally, run command to install Python 3.12:

sudo apt install python3.12

**Comment by DOOMMARINE117** [comment]
got it installed.

what about for gamescope?

**Comment by Anduin2017** [comment]
(I'm not familiar with Gamescope and didn't test the following steps. Follow with cautious.)

To install **Gamescope** on AnduinOS, follow these steps:

### 1. Add the Necessary Dependencies:
First, ensure that your system has the necessary dependencies installed for building Gamescope:

```bash
sudo apt update
sudo apt install build-essential cmake libxcb-randr0-dev libwayland-dev libxkbcommon-dev \
  libvulkan-dev vulkan-utils libdrm-dev libgbm-dev libxcomposite-dev \
  libxrandr-dev libgles2-mesa-dev libegl1-mesa-dev libxinerama-dev \
  libx11-xcb-dev libxcb-xinput-dev libxcb-keysyms1-dev git
```

### 2. Clone the Gamescope Repository:
You'll need to get the source code for Gamescope from its official repository. Use the following command to clone it:

```bash
git clone https://github.com/Plagman/gamescope.git
```

### 3. Build Gamescope:
Navigate to the cloned repository and build Gamescope:

```bash
cd gamescope
meson build
ninja -C build
```

### 4. Install Gamescope:
Once the build completes, install Gamescope using the following:

```bash
sudo ninja -C build install
```

### 5. Running Gamescope:
Now, you should be able to run Gamescope with a command like:

```bash
gamescope -w 1280 -h 720 -- %command%
```

Where `%command%` would be the game or application you're launching.

If you encounter any errors, let me know!

**Comment by DOOMMARINE117** [comment]
E: Unable to locate package vulkan-utils

 sudo ninja -C build install
sudo: ninja: command not found

**Comment by Anduin2017** [comment]
It seems you are encountering a few issues while installing **Gamescope**. Let’s address them one by one:

### 1. Missing `vulkan-utils`:
The `vulkan-utils` package might not be available in your repository. You can try the following to install Vulkan tools manually:
```bash
sudo apt install vulkan-tools
```

If that also doesn't work, it could be due to repository issues or package name differences in your distribution. In that case, you can install it via the Vulkan SDK:
```bash
sudo apt update
sudo apt install libvulkan-dev vulkan-tools
```

### 2. Missing `pkg-config`:
It looks like the build process is failing because `pkg-config` is not installed. Install it using:
```bash
sudo apt install pkg-config
```

### 3. Missing `cmake`:
The error suggests that CMake is not found. Install it using:
```bash
sudo apt install cmake
```

### 4. `libpipewire-0.3` Dependency:
It seems that `libpipewire-0.3` is missing. Try installing it with:
```bash
sudo apt install libpipewire-0.3-dev
```

### 5. `x11` Dependency:
For `x11`, you might need to install development packages:
```bash
sudo apt install libx11-dev
```

### 6. Restart the Build Process:
After installing the missing dependencies, try the build process again:
```bash
meson build
ninja -C build
```

Let me know if you encounter any further issues!

**Comment by DOOMMARINE117** [comment]
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-c99-designator: NO 
Compiler for C++ supports arguments -Wno-invalid-offsetof: YES 
Compiler for C++ supports arguments -Wno-unused-const-variable: YES 
Compiler for C++ supports arguments -Wno-volatile: YES 
Compiler for C++ supports arguments -Wno-deprecated-volatile: NO 
Compiler for C++ supports arguments -Wno-ignored-qualifiers: YES 
Compiler for C++ supports arguments -Wno-missing-braces: YES 
Compiler for C++ supports arguments -ffast-math: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libpipewire-0.3 found: YES 0.3.48
Library rt found: YES
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency hwdata found: NO (tried pkgconfig and cmake)
Run-time dependency x11 found: YES 1.7.5
Run-time dependency wayland-client found: NO (tried pkgconfig and cmake)

meson.build:49:0: ERROR: Dependency "wayland-client" not found, tried pkgconfig and cmake

A full log can be found at /home/talion117/gamescope/build/meson-logs/meson-log.txt
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory

**Comment by DOOMMARINE117** [comment]
made some progress. 

but ran into this.

 meson.build:79: WARNING: Building without hwdata pnp id support.
Check usable header "vulkan/vulkan.h" with dependency vulkan: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Build-time dependency wayland-scanner found: YES 1.20.0
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Run-time dependency wayland-protocols found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency wayland-protocols

protocol/meson.build:7:0: ERROR: Neither a subproject directory nor a wayland-protocols.wrap file was found.

A full log can be found at /home/talion/gamescope/build/meson-logs/meson-log.txt
ninja: Entering directory `build'
ninja: error: loading 'build.ninja': No such file or directory

**Comment by DOOMMARINE117** [comment]
i see the iso has been replaced as a torrent? so new update i think?

**Comment by DOOMMARINE117** [comment]
the gnome software it doesnt show aunduin os name anymore. thats only in gnome-software how to fix that? just says ubuntu(deb).when browsing

**Comment by Anduin2017** [comment]
Oh it couldn't AFAIK..

**Comment by DOOMMARINE117** [comment]
> Oh it couldn't AFAIK..

must be normal then.

what about gamescope issue? still cant get it to run. needs wayland-client

**Comment by Anduin2017** [comment]
I also have no idea. Sorry that I'm not a gamescope user...

**Comment by DOOMMARINE117** [comment]
no worries.  it can be challenging working on something like that. i manged to get it once yrs ago. but cant remember how.

**Comment by DOOMMARINE117** [comment]
got it to solve that error. now just need to solve this. protocol/meson.build:53:1: ERROR: File //usr/share/wayland-protocols/stable/linux-dmabuf/linux-dmabuf-v1.xml does not exist.

**Comment by DOOMMARINE117** [comment]
just foundout gamescope on debian wont work due to dependencies issues.

**Comment by DOOMMARINE117** [comment]
so it can work looks like. but its slow and such. but, im still determine to get it to work.

switching os is a pain in the ass, lol.

**Comment by DOOMMARINE117** [comment]
i have notice it freezes quite a bit on my pc handheld.

**Comment by Anduin2017** [comment]
Stall issue. Close.
