### ISSUE TITLE
日常娱乐软件 爱奇艺,腾讯视频的安装方法咨询

### ISSUE THREAD

**Issue by rdfsource** [Anduin2017/AnduinOS#9]
您好,当我进行娱乐活动时,如何在系统内优雅地装上 爱奇艺,并开启'帧绮映画 4K 60帧' 画质? 如何安装上 腾讯视频 ,并开启 '超高清 SDR 4K' 画质?

**Comment by Anduin2017** [comment]
你被闭源软件绑死了。闭源软件意味着除了开发它的公司，没人知道这些软件是如何工作和适配的。一旦受制于人，就会影响到自己的日常工作流。

尽可能选择开源的解决方案。

至于你说的brtfs，别担心。所有问题都是由于使用者对它的基本概念理解不够深刻导致的。只要你有基本的文件系统管理技能，就会玩得非常转。
